language: python

matrix:
  include:
  - python: 2.6
    env: TOXENV=py26-test
  - python: 2.6
    env: TOXENV=py26-requests-test
  - python: 2.6
    env: TOXENV=py26-wsgi
  - python: 2.6
    env: TOXENV=py26-flask

  - python: 2.7
    env: TOXENV=py27-test
  - python: 2.7
    env: TOXENV=py27-requests-test
  - python: 2.7
    env: TOXENV=py27-wsgi
  - python: 2.7
    env: TOXENV=py27-flask
  - python: 2.7
    env: TOXENV=py27-django18-django
  - python: 2.7
    env: TOXENV=py27-django19-django
  - python: 2.7
    env: TOXENV=py27-django110-django

  - python: 3.3
    env: TOXENV=py33-test
  - python: 3.3
    env: TOXENV=py33-requests-test
  - python: 3.3
    env: TOXENV=py33-wsgi

  - python: 3.4
    env: TOXENV=py34-test
  - python: 3.4
    env: TOXENV=py34-requests-test
  - python: 3.4
    env: TOXENV=py34-wsgi

  - python: 3.5
    env: TOXENV=py35-test
  - python: 3.5
    env: TOXENV=py35-requests-test
  - python: 3.5
    env: TOXENV=py35-wsgi
  - python: 3.5
    env: TOXENV=py27-django18-django
  - python: 3.5
    env: TOXENV=py27-django19-django
  - python: 3.5
    env: TOXENV=py27-django110-django
  - python: 3.5
    env: TOXENV=py35-lint

install: travis_retry pip install coveralls tox

script:
  - tox

after_success:
  - coveralls
